CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_catalogue_id BIGINT UNSIGNED DEFAULT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(225) NOT NULL,
    phone VARCHAR(20) NOT NULL UNIQUE,
    address VARCHAR(225) DEFAULT NULL,
    image VARCHAR(255) DEFAULT NULL,  -- tăng kích thước trường image
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_user_catalogue_id FOREIGN KEY (user_catalogue_id) REFERENCES user_catalogue(id)
    ON DELETE CASCADE
);
